<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/25
 * Time: 9:51
 */
namespace app\index\controller;
use think\Controller;

class Common  extends Controller{
    private $redis;
    function _initialize()
    {
//        $this->redis = new \Redis();
//        $this->redis->connect('127.0.0.1', 6379);
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}