<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/9/23 0023
 * Time: 9:58
 */
namespace app\admin\model;
use think\Model;
class Purchase_operation extends Model{
    private $post;
    private $edition;
    private $types;
    /**
     * @param $data
     * @return $this
     * 要添加的数据
     */
    function Set_data($data){
        $this->post =  $data;
        return $this;
    }
    function Set_type($type){
        $this->types = $type;
        return $this;
    }

    /**生成版本号
     * @param $edition
     * @return $this
     */
    function Set_edition($edition=''){
        $edition = date('Ymdhi').mt_rand(0,999);
        $this->edition = $edition;
        return $this;
    }

    /**简单的数据校验
     * @param $data 要验证的变量名称
     * @return mixed 返回结果
     */
    function vali_data($data){
        if(!isset($this->{$data})){
            exception('参数'.$data.'未传值');
        }
        return $this->{$data};
    }

    public function initialize()
    {
//        if(!isset($this->edition)){
//            return $this->Set_edition();
//        }
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**批量进仓
     * @return mixed
     */
    function Batch_add(){
        /*验证提交数据*/
        $data =  $this->vali_data('post');
        $type = $this->vali_data('types');
        /*进出仓*/
        if($type == true){
            $operation_type = 0;
        }else{
            $operation_type = 1;
        }
        $time = time();
        $edition = date('Ymd');
        $edition = $edition.mt_rand(0,99);
        $newdata =  array();
        foreach ($data as $k=>$v){
            $newdata[]=['purchase_id'=>$k,'goods_num'=>$v,'operation_time'=>$time,
                'status'=>1,'operation_type'=>$operation_type,'add_id'=>session('uid'),
                'edition'=>$edition];
        }
        //dump($newdata);exit();
        $result = $this->insertAll($newdata);
        //dump($newdata);
        if(!$result){
            exception('附表进仓错误');
        }
        return $edition;
    }
}