<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/25
 * Time: 10:23
 */
namespace app\admin\controller;
use think\Controller;
use app\common;
class  Base extends  common{
    private $userInfo;

    public function _initialize()
    {
       parent::_initialize(); // TODO: Change the autogenerated stub
        /*判断用户是否登录*/

        /*获取用户缓存*/

        /*判断用户缓存是否存在*/

        /*存在获取缓存*/

        /*不存在生成缓存*/

        /*获取当前页面的权限id*/

        /*获取用户的权限集合*/

        /*进行比对*/

    }

    public function check($url_id,$uid)
    {
        if (!$this->_config['auth_on'])
            return true;
        $authList = $this->getAuthList($uid); //获取用户需要验证的所有有效规则列表
        /*合并两个权限*/
        $authList = array_merge($this->_auth,$authList);
        //  $auth_user = $this->check_url($authList,$url,$mode);
        //return $auth_user;
    }
}
