<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/25
 * Time: 10:23
 */
namespace app\admin\controller;
use Auth\Auth;
use think\Controller;
use app\common;
class  Base extends  common{
    private $userInfo;
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        if(!session('uid')){
            $this->error('请先登录',Url('admin/share/login'));
        }
        /*判断用户是否登录*/
        try{
            if(session('uid')!=1 && session('uid')){
                $auth =  new Auth();
                $url = get_url();
                $auth_vlit = $auth->check($url,session('uid'));
                if($auth_vlit!=true){
                    $img =__ADMIN_LAYER__."/layui/images/404.jpg";
                    exit(
                         widget("admin/Webplug/webplug",
                                json_encode(
                                    array('config'=>array('tips'=>'你没有权限访问','img'=>$img)
                                        ,'plug'=>'error_web')
                                )
                         )
                    );
                }
            }
        }catch( \Exception $e){
            $this->error($e->getMessage());
        }
    }
    function Set_ListPage($data,$view ='public/table_list',$request_url){
        $this->assign('config',$data);
        $this->assign('request_url',$request_url);
        return view($view);
    }

}
