<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2017/8/25
     * Time: 11:51
     */
    namespace app\admin\controller;
    use Plug\Plug;
    use app\admin\model\Group as Groups;
    class  Group extends  Base{
        private $model;
        private $post;
        function __construct()
        {
            parent::__construct(); // TODO: Change the autogenerated stub
            $this->model = new Groups;
            $this->post = input('post.');
        }

        public function index(){
            /*获取配置*/
            $data = $this->Get_sys('index',array());
            /*页面输出*/
            return  $this->Set_ListPage($data['config'],"public/table_list",$data['request_url']);
        }
        public function getlist(){
            $post= input('post');$page = input('page');
            $post =  isset($post)? $post : '';
            $page =  isset($page)?$page :1;
            /*查询字段名称*/
            $field = 'a.id,a.group_name,a.add_time,a.status,a.add_id,b.username as add_username ';
            /*获取页面数据*/
            $data = $this->model->Set_post($post)->Set_page($page)->Set_fied($field)->Set_page_num(10)->get_list();
            /*获取配置*/
            $data_config = $this->Get_sys('getlist');
            $data['config'] =$data_config['config'];
            /*页面输出*/
            return $this->Set_ListPage($data,"public/table_list_cp",$data_config['request_url']);
        }
        public function info(){
            try {
                $id = input('id');
                /*获取修改数据*/
                if($id){
                    $field='id,username,nickname,mobile,password,group';
                    $data_arr = $this->model->find_user_Info($id,'',$field);
                    /*获取配置*/
                    $data = $this->Get_sys('info',$data_arr);
                    return $this->Set_ListPage($data['config'],"public/info",$data['request_url'],$data_arr);
                }else{
                    /*获取配置*/
                    $data = $this->Get_sys('info');
                    return $this->Set_ListPage($data['config'],"public/info",$data['request_url']);
                }
            }catch( \Exception $e){
                return ajax_return(false,$e->getMessage());
            }
        }
        public function add(){
           return  $this->info();
        }
        /**
         * 获取配置参数
         */
        protected  function Get_sys($page_name='',$data=array()){
            $Plug = new Plug();
            switch($page_name){
                case 'index':
                    $data['config'] =  $Plug->Set_TabTop(1)->index('Set_Group_TabTop');
                    $data['request_url']['get_list'] =  url('getlist');
                    $data['request_url']['add_url'] = url('add');
                    break;
                case 'info':
                    if($data){
                        $data['config'] =$Plug->Set_Value($data)->index('Set_Group_Info');
                    }else{
                        $data['config'] =$Plug->index('Set_Group_Info');
                    }
                    $data['request_url']['submit_url'] = url('update');
                    break;
                case 'getlist':
                    $data['config']= $Plug->index('Set_Group_TabBottom');
                    $data['request_url']['edit'] = '/admin/User/info/id/';
                    break;
            }
            return $data;
        }

        function update(){
            if(request()->isPost()){
                try{
                    $result = $this->model->set_post($this->post)->update_data();
                    return $result;
                }catch( \Exception $e){
                    return ajax_return(false,$e->getMessage());
                }
            }
        }
    }