<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/24
 * Time: 14:08
 */
namespace app\admin\controller;
use app\admin\controller\Base;
use app\model\Admin;

class Index extends  Base{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
      return view();
    }
}