<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/24
 * Time: 14:08
 */
namespace app\admin\controller;
use app\admin\controller\Base;
use app\admin\model\admin;

class Index extends  Base{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
     //   echo  '好气哦';
        $admin = new admin();
        $data['username'] = 'test';
        $data['password'] = '123456';
        $admin->admin_add();
    }
}