<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2017/7/7
     * Time: 10:59
     */
    namespace app\admin\controller;
    use think\Controller;
    use app\common;
    class  Nav extends  common{
        private $model;
        private $post;
        public function _initialize()
        {
            $this->post =  input('post.');
            parent::_initialize(); // TODO: Change the autogenerated stub
          //  $this->model = new \app\admin\logic\user();
        }
        public function index(){

            return view();
        }
        public function info(){

            return view();
        }
        public function update(){

        }

    }