<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2017/7/7
     * Time: 10:59
     */
    namespace app\admin\controller;

    class  Nav extends  Base{
        private $model;
        private $post;
     //   private $web_config ;
        public function _initialize()
        {
            /*实例化处理层*/
            $this->model = new \app\admin\logic\nav();
            $this->post =  input('post.');
           // parent::_initialize(); // TODO: Change the autogenerated stub
        }
        public function index(){

            return view();
        }
        /*导航详情页*/
        public function info(){
            $view = db('view')->where('id = 1')->field('content')->find();
            /*配置数组*/
            $view_plug = array();
            /*获取配置*/
            $view_plug =  $this->model->get_view($view)->set_config('info');
            /*页面输出*/
            $this->assign('submit_url',Url('update'));
            $this->assign('view_plug',$view_plug);
            return view();
        }
        public function update(){
            if(request()->isPost()){
                return $this->model->set_post($this->post)->update_data();
            }
        }

        /**
         * 左侧菜单返回
         * @return mixed
         */
        public function leftnav(){
            $array =   $this->model->get_Allmenu();
           return       $array;
        }
        public function navlist(){
            return view();
        }
    }