<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/2
 * Time: 11:15
 */
namespace app\admin\controller;
use app\common;
class Pubilc extends  common{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function  login(){

    }

    public function loginout(){

    }
}