<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/23
 * Time: 14:47
 */
namespace app\admin\controller;
use Plug\Plug;
use think\Controller;
use think\Url;

class  Purchase extends  Base{
    private $model;
    private $post;
    public function __construct()
    {
        $this->post =  input('post.');
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Purchase();
    }

    /**用户列表页
     * @return \think\response\View
     */
    public function index(){
        /*获取配置*/
        $data = $this->Get_sys('index',array());
        /*页面输出*/
        return  $this->Set_ListPage($data['config'],"public/table_list",$data['request_url']);
    }
    /*列表页面*/
    public function getlist(){
        /*查询字段名称*/
        $field = 'a.id,a.goods_name,a.goods_specification,a.goods_version,a.shape_code,a.goods_pice,
                a.goods_num,a.add_time,a.data_node,a.update_time';
        /*获取页面数据*/
        $data = $this->model->Set_Post(input('post'))->Set_page(input('page'))->Set_page_num(10)->set_fields($field)->getList();
        //dump($data);
        /*获取配置*/
        $data_config = $this->Get_sys('getlist');
        $data['config'] =$data_config['config'];
        $data_config['request_url']['edit'] =Url();
        /*页面输出*/
        return $this->Set_ListPage($data,"public/table_list_cp",$data_config['request_url']);
    }
    /*批量添加货物*/
    function Excel_Import_Goods(){
        if(request()->isPost()){
            $array=array(
                'ids','goods_name', 'goods_specification','goods_version','shape_code','goods_pice'
            );
            $arr = $this->model->Set_Post($_POST)->Excel_Goods($array,2);
            return  $this->model->foreach_select($arr);
        }else{
            $data = $this->Get_sys('Excel_Import_Goods');
            return $this->Set_ListPage($data['config'],"public/info",$data['request_url']);
        }
    }

    /**
     * 选择货物
     */
    public function choice_goods (){
        if(request()->isPost()){
            try{
                $goods_id = input('goods_id');
                if(!$goods_id || empty($goods_id)){
                    exception('请选择货物再进行操作');
                }
                $goods_arr = array_filter(array_unique(explode(',',$goods_id)));
                $map['id'] = array('in',$goods_arr);
                $result = $this->model->Set_map($map)->Set_fields('id,goods_name,goods_specification,goods_version,shape_code')->get_select();
                $fields = array(
                    array('id','标记','str'),
                    array('goods_name','货物名称'),
                    array('goods_specification','规格'),
                    array('goods_version','型号'),
                    array('shape_code','条形码','str'),
                    array('num','数量')
                );
                $this->model->Set_Post($result)->get_export($fields);
            }catch( \Exception $e){
                return $this->error($e->getMessage());
            }
        }else{
            $data = $this->Get_sys('choice_goods');
            return $this->Set_ListPage($data['config'],"public/info",$data['request_url'],'',false);
        }
    }

    /**
     * ajax搜索货物
     */
    public function ajax_search_goods(){
        if(request()->isAjax()){
            /*组合查询条件*/
            $search_name = input('search_name_');
            $map = array();
            if($search_name){
                $map['goods_name|goods_specification|goods_version|shape_code'] =array('like','%'.Trim($search_name).'%');
            }
            $result = $this->model->Set_map($map)->Set_fields('id,goods_name,goods_specification,goods_version,shape_code')->get_select();
            return  json_encode(array('status'=>true,'info'=>$this->model->get_array_assembly($result),'url'=>''));
        }
    }

    /**
     * 进销存
     */
    public function Enters_sells_saves(){
        if(request()->isPost()){
           try{
               $post = input('post.');
               if(!isset($post['file_url']) || empty($post['file_url'])){
                    exception(‘请先上传文件’);
               }
               /*出仓否则为进仓*/
               if(!isset($post['goods_name'])){
                   $post['goods_name'] = false;
               }
               $array=array(
                   'id','goods_name', 'goods_specification','goods_version','shape_code','goods_num'
               );
               $arr = $this->model->Set_Post($post)->Excel_Goods($array,3);
               return $this->model->Set_Post($post)->handling_Enters_sells_saves($arr);
           } catch( \Exception $e){
               return $this->error($e->getMessage());
           }

        }else{
            $data = $this->Get_sys('Enters_sells_saves');
            return $this->Set_ListPage($data['config'],"public/info",$data['request_url'],'');
        }
    }
    /*添加页面*/
    public function add(){
      return  $this->info();
    }

    /*详情页*/
    public function info(){
        try {
            $id = input('id');
            /*获取修改数据*/
            if($id){
                $field='*';
                $map['id'] = $id;
                $data_arr = $this->model->Set_map($map)->Set_fields($field)->find_Purchase_Info();
                /*获取配置*/
                $data = $this->Get_sys('info',$data_arr);
                return $this->Set_ListPage($data['config'],"public/info",$data['request_url'],$data_arr);
            }else{
                /*获取配置*/
                $data = $this->Get_sys('info');
                return $this->Set_ListPage($data['config'],"public/info",$data['request_url']);
            }
        }catch( \Exception $e){
            return ajax_return(false,$e->getMessage());
        }
    }

    /*修改函数*/
    public function update(){
        if(request()->isPost()){
           try{
               $result = $this->model->Set_Post($this->post)->update_data();
               return $result;
           }catch( \Exception $e){
               return ajax_return(false,$e->getMessage());
           }
        }
    }
    /**
     * 获取配置参数
     */
    protected  function Get_sys($page_name='',$data=array()){
        $Plug = new Plug();
        switch($page_name){
            /*列表配置*/
            case 'index':
                $data['config'] = $Plug->Set_TabTop(1)->index('Set_Purchase_TabTop');
                $data['request_url']['get_list'] =  url('/admin/Purchase/getlist/menu_id/21');
                break;
            /*详情配置*/
            case 'info':
                if($data){
                    $data['config'] =$Plug->Set_Value($data)->index('Set_Purchase_Info');
                }else{
                    $data['config'] =$Plug->index('Set_Purchase_Info');
                }
                $data['request_url']['submit_url'] = url('update');
                break;
            /*ajax列表加载*/
            case 'getlist':
                $data['config']= $Plug->index('Set_Purchase_TabBottom');
                break;
            /*批量添加货物页面*/
            case 'Excel_Import_Goods':
                $data['config']= $Plug->index('Set_Excel_Import_Goods_Info');
                $data['request_url']['submit_url'] = url('Excel_Import_Goods');
                break;
            /*选择货物导出模板*/
            case 'choice_goods':
                $data['config']= $Plug->index('Set_Choice_Goods');
                $data['request_url']['submit_url'] = url('choice_goods');
                break;
            case'Enters_sells_saves':
                $data['config']= $Plug->index('Set_Enters_sells_saves');
                $data['request_url']['submit_url'] = url('Enters_sells_saves');
                break;
        }
        return $data;
    }
}
