<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/23
 * Time: 14:47
 */
namespace app\admin\controller;
use app\admin\model\Admin;
use Plug\Plug;
use think\Controller;

class  Purchase extends  Base{
    private $model;
    private $post;
    public function __construct()
    {
        $this->post =  input('post.');
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Purchase();
    }

    /**用户列表页
     * @return \think\response\View
     */
    public function index(){
        /*获取配置*/
        $data = $this->Get_sys('index',array());
        /*页面输出*/
        return  $this->Set_ListPage($data['config'],"public/table_list",$data['request_url']);
    }
    /*列表页面*/
    public function getlist(){
        /*查询字段名称*/
        $field = 'a.id,a.goods_name,a.goods_specification,a.goods_version,a.shape_code,a.goods_pice,
                a.goods_num,a.add_time,a.data_node,a.update_time';
        /*获取页面数据*/
        $data = $this->model->Set_Post(input('post'))->Set_page(input('page'))->Set_page_num(10)->set_fields($field)->getList();
        /*获取配置*/
        $data_config = $this->Get_sys('getlist');
        $data['config'] =$data_config['config'];
        /*页面输出*/
        return $this->Set_ListPage($data,"public/table_list_cp",$data_config['request_url']);
    }

    /*添加页面*/
    public function add(){
      return  $this->info();
    }

    /*详情页*/
    public function info(){
        try {
            $id = input('id');
            /*获取修改数据*/
            if($id){
                $field='id,username,nickname,mobile,password,group';
                $data_arr = $this->model->find_user_Info($id,'',$field);
                /*获取配置*/
                $data = $this->Get_sys('info',$data_arr);
                return $this->Set_ListPage($data['config'],"public/info",$data['request_url'],$data_arr);
            }else{
                /*获取配置*/
                $data = $this->Get_sys('info');
                return $this->Set_ListPage($data['config'],"public/info",$data['request_url']);
            }
        }catch( \Exception $e){
            return ajax_return(false,$e->getMessage());
        }
    }

    /*修改函数*/
    public function update(){
        if(request()->isPost()){
           try{
               $result = $this->model->Set_Post($this->post)->update_data();
               return $result;
           }catch( \Exception $e){
               return ajax_return(false,$e->getMessage());
           }
        }
    }
    /**
     * 获取配置参数
     */
    protected  function Get_sys($page_name='',$data=array()){
        $Plug = new Plug();
        switch($page_name){
            case 'index':
                $data['config'] = $Plug->Set_TabTop(1)->index('Set_Purchase_TabTop');
                $data['request_url']['get_list'] =  url('admin/getlist');
                $data['request_url']['add_url'] = url('add');
                break;
            case 'info':
                if($data){
                    $data['config'] =$Plug->Set_Value($data)->index('Set_Purchase_Info');
                }else{
                    $data['config'] =$Plug->index('Set_Purchase_Info');
                }
                $data['request_url']['submit_url'] = url('update');
                break;
            case 'getlist':
                $data['config']= $Plug->index('Set_Purchase_TabBottom');
                break;
        }
        return $data;
    }
}
