<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/23
 * Time: 14:47
 */
namespace app\admin\controller;
use app\admin\model\Admin;
use Plug\Plug;
use think\Controller;
use think\Url;

class  Purchase extends  Base{
    private $model;
    private $post;
    public function __construct()
    {
        $this->post =  input('post.');
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\model\Purchase();
    }

    /**用户列表页
     * @return \think\response\View
     */
    public function index(){
        /*获取配置*/
        $data = $this->Get_sys('index',array());
        /*页面输出*/
        return  $this->Set_ListPage($data['config'],"public/table_list",$data['request_url']);
    }
    /*列表页面*/
    public function getlist(){
        /*查询字段名称*/
        $field = 'a.id,a.goods_name,a.goods_specification,a.goods_version,a.shape_code,a.goods_pice,
                a.goods_num,a.add_time,a.data_node,a.update_time';
        /*获取页面数据*/
        $data = $this->model->Set_Post(input('post'))->Set_page(input('page'))->Set_page_num(10)->set_fields($field)->getList();
        /*获取配置*/
        $data_config = $this->Get_sys('getlist');
        $data['config'] =$data_config['config'];
        $data_config['request_url']['edit'] =Url();
        /*页面输出*/
        return $this->Set_ListPage($data,"public/table_list_cp",$data_config['request_url']);
    }
    /*批量添加货物*/
    function Excel_Import_Goods(){
        if(request()->isPost()){
           return $this->model->Set_Post($_POST)->Excel_Goods();
        }else{
            $data = $this->Get_sys('Excel_Import_Goods');
            return $this->Set_ListPage($data['config'],"public/info",$data['request_url']);
        }
    }

    /**
     * 选择货物
     */
    public function choice_goods (){
        if(request()->isPost()){

        }else{
            $data = $this->Get_sys('choice_goods');
            return $this->Set_ListPage($data['config'],"public/info",$data['request_url']);
        }
    }

    /**
     * ajax搜索货物
     */
    public function ajax_search_goods(){
        if(request()->isAjax()){

        }
    }
    /*添加页面*/
    public function add(){
      return  $this->info();
    }

    /*详情页*/
    public function info(){
        try {
            $id = input('id');
            /*获取修改数据*/
            if($id){
                $field='*';
                $map['id'] = $id;
                $data_arr = $this->model->Set_map($map)->Set_fields($field)->find_Purchase_Info();
                /*获取配置*/
                $data = $this->Get_sys('info',$data_arr);
                return $this->Set_ListPage($data['config'],"public/info",$data['request_url'],$data_arr);
            }else{
                /*获取配置*/
                $data = $this->Get_sys('info');
                return $this->Set_ListPage($data['config'],"public/info",$data['request_url']);
            }
        }catch( \Exception $e){
            return ajax_return(false,$e->getMessage());
        }
    }

    /*修改函数*/
    public function update(){
        if(request()->isPost()){
           try{
               $result = $this->model->Set_Post($this->post)->update_data();
               return $result;
           }catch( \Exception $e){
               return ajax_return(false,$e->getMessage());
           }
        }
    }
    /**
     * 获取配置参数
     */
    protected  function Get_sys($page_name='',$data=array()){
        $Plug = new Plug();
        switch($page_name){
            /*列表配置*/
            case 'index':
                $data['config'] = $Plug->Set_TabTop(1)->index('Set_Purchase_TabTop');
                $data['request_url']['get_list'] =  url('/admin/Purchase/getlist/menu_id/21');
                break;
            /*详情配置*/
            case 'info':
                if($data){
                    $data['config'] =$Plug->Set_Value($data)->index('Set_Purchase_Info');
                }else{
                    $data['config'] =$Plug->index('Set_Purchase_Info');
                }
                $data['request_url']['submit_url'] = url('update');
                break;
            /*ajax列表加载*/
            case 'getlist':
                $data['config']= $Plug->index('Set_Purchase_TabBottom');
                break;
            /*批量添加货物页面*/
            case 'Excel_Import_Goods':
                $data['config']= $Plug->index('Set_Excel_Import_Goods_Info');
                $data['request_url']['submit_url'] = url('Excel_Import_Goods');
                break;
            case 'choice_goods':
                $data['config']= $Plug->index('Set_Choice_Goods');
                $data['request_url']['submit_url'] = url('choice_goods');
                break;
        }
        return $data;
    }
}
