<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/2
 * Time: 11:15
 */
namespace app\admin\controller;
use app\common;
class Share extends  common{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function  login(){
       if(input('post.')){
           /*调用登陆类*/
           echo  1;
           exit();
       }
        return view();
    }

    public function loginout(){

    }
}