<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/23
 * Time: 14:47
 */
namespace app\admin\controller;
use app\admin\model\Admin;
use think\Controller;
class  User extends  Base{
    private $model;
    private $post;
    public function __construct()
    {
        $this->post =  input('post.');
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->model = new Admin();
    }

    public function index(){
        return view();
    }
    public function add(){
        $this->info();
    }
    public function info(){
        try {
            $view = db('view')->where('id = 2')->field('content')->find();
            /*配置数组*/
            $view_plug = array();
            /*获取配置*/
            $view_plug = $this->model->get_view($view)->set_config('info');
            /*页面输出*/
            $this->assign('submit_url', Url('update'));
            $this->assign('view_plug', $view_plug);
            return view();
        }catch( \Exception $e){
            return ajax_return(false,$e->getMessage());
        }
    }
    public function update(){
        if(request()->isPost()){
           try{
               $result = $this->model->set_post($this->post)->update_data();
               return $result;
           }catch( \Exception $e){
               return ajax_return(false,$e->getMessage());
           }
        }
    }
    public function accredit(){
    }
    public function vali_data(){
        if(request()->isPost()){
            return $this->model->set_post($this->post)->vali_data();
        }
    }
}
