<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/23
 * Time: 14:47
 */
namespace app\admin\controller;
use app\admin\controller\Base;
use app\model\Admin;
use think\Controller;
use app\common;
class  User extends  common{
    private $model;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->model = new \app\admin\logic\user();
    }

    public function index(){

    }
    public function info(){
        return view();
    }
    public function update(){
        if(request()->isPost()){

        }
    }
    public function accredit(){

    }
    public function vali_data(){
        if(request()->isPost()){
            $post = input('post.');
            return $this->model->vali_data();
        }
        //$this->model->vali_data($field,$value);
    }
}
