<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/23
 * Time: 14:47
 */
namespace app\admin\controller;
use app\admin\model\Admin;
use Plug\Plug;
use think\Controller;

class  User extends  Base{
    private $model;
    private $post;
    private $test;
   // private $plug;
    public function __construct()
    {
        $this->post =  input('post.');
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->model = new Admin();
     //   $this->plug = new Plug();
        $this->test=array('lib'=>1);
    }

    /**用户列表页
     * @return \think\response\View
     */
    public function index(){
        /*获取配置*/
        $data = $this->Get_sys('index',array());
        /*页面输出*/
        return  $this->Set_ListPage($data['config'],"public/table_list",$data['request_url']);
    }

    public function getlist(){
        /*查询字段名称*/
        $field = 'a.id,a.username,a.nickname,a.mobile,a.add_time,a.status,a.last_login_time,a.last_login_ip,b.group_name,c.username as add_username ';
        /*获取页面数据*/
        $data = $this->model->set_post(input('post'))->set_page(input('page'))->set_field($field)->getList();
        /*获取配置*/
        $data_config = $this->Get_sys('getlist');
        $data['config'] =$data_config['config'];
        /*页面输出*/
        return $this->Set_ListPage($data,"public/table_list_cp",$data_config['request_url']);

    }
    /*添加页面*/
    public function add(){
      return  $this->info();
    }
    /*详情页*/
    public function info(){
        try {
            $id = input('id');
            /*获取修改数据*/
            if($id){
                $field='id,username,nickname,mobile,password,group';
                $data_arr = $this->model->find_user_Info($id,'',$field);
                /*获取配置*/
                $data = $this->Get_sys('info',$data_arr);
                return $this->Set_ListPage($data['config'],"public/info",$data['request_url'],$data_arr);
            }else{
                /*获取配置*/
                $data = $this->Get_sys('info');
                return $this->Set_ListPage($data['config'],"public/info",$data['request_url']);
            }
        }catch( \Exception $e){
            return ajax_return(false,$e->getMessage());
        }
    }
    /*修改函数*/
    public function update(){
        if(request()->isPost()){
           try{
               $result = $this->model->set_post($this->post)->update_data();
               return $result;
           }catch( \Exception $e){
               return ajax_return(false,$e->getMessage());
           }
        }
    }
    public function accredit(){
    }
    public function vali_data(){
        if(request()->isPost()){
            return $this->model->set_post($this->post)->vali_data();
        }
    }

    /**
     * 获取配置参数
     */
    protected  function Get_sys($page_name='',$data=array()){
        $Plug = new Plug();
        switch($page_name){
            case 'index':
                $data['config'] = $Plug->Set_TabTop(1)->index('Set_User_TabTop');
                $data['request_url']['get_list'] =  url('getlist');
                $data['request_url']['add_url'] = url('add');
                break;
            case 'info':
                if($data){
                    $data['config'] =$Plug->Set_Value($data)->index('Set_User_Info');
                }else{
                    $data['config'] =$Plug->index('Set_User_Info');
                }
                $data['request_url']['submit_url'] = url('update');
                break;
            case 'getlist':
                $data['config']= $Plug->index('Set_User_TabBottom');
                $data['request_url']['edit'] = '/admin/User/info/id/';
                break;
        }
        return $data;
    }
}
