<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2017/7/13
     * Time: 15:37
     */
    namespace app\admin\controller;
    use app\admin\widget\Webplug;
    use think\Controller;
    use think\Debug;
    use app\admin\model\View as View_model;
    class  View extends  Base{
        private $model;
        private $post;
        function __construct()
        {
            $this->post =  input('post.');
            $this->model = new View_model;
            parent::__construct(); // TODO: Change the autogenerated stub
        }
        /*主页*/
        public function index(){
          //  Logic_View::select_view();
            return view();
        }
        /*添加页*/
        public function add(){
            return view('info');
        }
        public function edit(){
            return view('info');
        }
        /*详情页*/
        public function info(){
            $url = APP_PATH.'/admin/view/widget';
            $id = input('id');
            $plug =  get_pant_file($url);
            $this->assign('plug',$plug);
            $this->assign('submit_url',Url('update'));
            return view();
        }

        /*添加修改提交页*/
        public function update(){
            if(request()->isPost()){
                try{
                    $result = $this->model->set_post($this->post)->update_data();
                    return $result;
                }catch( \Exception $e){
                    return ajax_return(false,$e->getMessage());
                }
            }
        }

        /**
         * 列表测试页面
         * @return \think\response\View
         */
        public function  newsList(){
            try{
                $config = $this->model->get_list_conf("index_config");
                $request_url['get_list'] =  url('getlist');
                return  $this->Set_ListPage($config,"public/table_list",$request_url);
            }catch( \Exception $e){
                $this->error($e->getMessage());
            }
        }

        /**
         * ajax 返回数据
         *
         */
        public function getlist(){
            try{
                /*查询字段名称*/
                $field = 'a.id,a.view_name as title,a.add_id,a.add_time,a.status,b.username';
                $page = input('page');
                $result = $this->model->set_post($this->post)->set_field($field)->set_page($page)->getList();
                $request_url['edit'] = '/admin/view/info/id/';
                return $this->Set_ListPage($result,"public/table_list_cp",$request_url);
            }catch( \Exception $e){
              return ajax_return(false,$e->getMessage());
            }
        }
    }