<?php
    /**
     * Created by PhpStorm.
     * User: Administrator
     * Date: 2017/7/13
     * Time: 15:37
     */
    namespace app\admin\controller;
    use app\admin\widget\Webplug;
    use think\Controller;
    use app\common;
    use think\Debug;
    use think\Url;

    class  View extends  common{
        private $model;
        private $post;
        function _initialize()
        {
            $this->post =  input('post.');
            $this->model = new \app\admin\logic\view();
            parent::_initialize(); // TODO: Change the autogenerated stub
        }

        public function index(){
            return view();
        }
        public function add(){
            return view('info');
        }
        public function info(){
            $webplug =  new Webplug();
            $plug = get_class_methods(get_class($webplug));
            $this->assign('plug',$plug);
            $this->assign('submit_url',Url('update'));
            return view();
        }

        public function update(){
            if(request()->isPost()){
                return $this->model->set_post($this->post)->update_data();
            }
        }
    }